# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Model' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FLUtilities', :git => 'https://github.com/Nickelfox/FLUtilities.git'
  pod 'FoxAPIKit', :git => 'https://github.com/Nickelfox/FoxAPIKit.git', :branch => 'refactor'
  pod 'ReactiveSwift'
end

target 'NewsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveSwift'
  pod 'ReactiveCocoa'
end
