# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Model' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "FLUtilities", :git => 'https://github.com/Nickelfox/FLUtilities.git'
  pod "APIClient", :git => 'https://github.com/Nickelfox/APIClient.git'
  pod 'ReactiveSwift', '~> 2.0'
  # pod ‘SDWebImage’, ‘~> 3.8’
  # pod ‘MBProgressHUD’, ‘~> 1.0’
  # pod ‘PaginationUIManager’ , ‘~> 0.1.0’
  # Pods for Model

end

target 'NewsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveSwift', '~> 2.0'
  pod 'ReactiveCocoa', '~> 6.0'
  # Pods for NewsApp

end
